name = "muvi"

main = "./server.js"
workers_dev = true
compatibility_date = "2024-07-19"

[site]
bucket = "./build/client"

[build]
command = "pnpm run build"

[[d1_databases]]
binding = "DB"
database_name = "muvi"
database_id = "8c536752-ab98-4cfc-bfa3-cc819a5520b1"
