name = "muvi"

main = "./server.js"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
bucket = "./build/client"

[build]
command = "pnpm run build"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "muvi"
database_id = "8c536752-ab98-4cfc-bfa3-cc819a5520b1"
